{
 "title": "PocDynaActiveGate01",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Average",
   "type": "gauge",
   "description": "CPU Average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    }
   ]
  },
  {
   "title": "Network bandwidth consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    }
   ]
  },
  {
   "title": "DiskI/O RW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "1= Available\n0= Unavailable",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "VmAvailabilityMetric",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    }
   ]
  },
  {
   "title": "OS Read/Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Compute/virtualMachines",
        "region": "westeurope",
        "resourceGroup": "AZRGPICNTR-MONITORING",
        "resourceName": "PocDynaActiveGate01",
        "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "34dc1737-2f01-4c21-8311-d41156f78fd2"
    }
   ]
  }
 ]
}