{
 "title": "azlvautolsrv02",
 "description": "Dashboard for InfluxDB",
 "time": { "from": "2023-06-23T00:07:36.042Z", "to": "2023-06-23T12:07:36.042Z" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "Checks CPU Usage last hour",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Linux\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"azlvautolsrv02\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "stat",
   "description": "RAM Usage ",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Linux\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"azlvautolsrv02\")"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "description": "Amount of bytes read",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"Linux\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"sda\" or r[\"name\"] == \"sdb\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"azlvautolsrv02\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "timeseries",
   "description": "Amount of bytes written",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"Linux\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"sda\" or r[\"name\"] == \"sdb\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"azlvautolsrv02\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Uptime in hours",
   "type": "logs",
   "gridPos": { "h": 2, "w": 3, "x": 13, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"Linux\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_format\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"azlvautolsrv02\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "gauge",
   "description": "Disk Usage %",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Linux\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"sda2\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"azlvautolsrv02\")"
    }
   ]
  }
 ]
}