{
 "title": "i-023bf2e62ddb0ec80",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Average",
   "type": "gauge",
   "description": "CPU Average",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-023bf2e62ddb0ec80" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DiskI/O RW Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-0854ecedd60b1c861" },
     "metricName": "DiskReadBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-0854ecedd60b1c861" },
     "metricName": "DiskWriteBytes",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Network bandwidth bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-023bf2e62ddb0ec80" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "InstanceId": "i-023bf2e62ddb0ec80" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "0= Available\n1= Unavailable",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dimensions": { "InstanceId": "i-023bf2e62ddb0ec80" },
     "metricName": "StatusCheckFailed",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}