{
 "title": "AZLVICNTRWDEV01",
 "description": "Dashboard for InfluxDB",
 "time": { "from": "2023-06-29T06:07:36.000Z", "to": "2023-06-29T09:07:36.000Z" },
 "panels": [
  {
   "title": "CPU %",
   "type": "gauge",
   "description": "Checks CPU Usage last hour",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "stat",
   "description": "RAM Usage ",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")"
    }
   ]
  },
  {
   "title": "Read Bytes",
   "type": "timeseries",
   "description": "Amount of bytes read",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"C:\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Bytes written",
   "type": "timeseries",
   "description": "Amount of bytes written",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"C:\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "table",
   "description": "Running processes in Windows machine",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"win_services\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"state\" and r[\"_value\"] == 4)\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  |> distinct(column: \"service_name\")\r\n  |> map(fn: (r) => ({Name: r.service_name}))"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "gauge",
   "description": "Disk Usage %",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"C:\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")"
    }
   ]
  },
  {
   "title": "Download Speed Mbps",
   "type": "timeseries",
   "description": "Download speeds",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_speed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"download\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  "
    }
   ]
  },
  {
   "title": "Upload Speed Mbps",
   "type": "timeseries",
   "description": "Upload speeds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internet_speed\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"upload\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  "
    }
   ]
  },
  {
   "title": "Uptime in hours",
   "type": "logs",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"Windows\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_format\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"AZLVICNTRWDEV01\")\r\n  |> last()\r\n"
    }
   ]
  }
 ]
}