version: '3.7'
services:
  influxdb:
    image: influxdb:2.7.0
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - source: influxdb
        target: /var/lib/influxdb2
        type: volume
    restart: always
volumes:
  influxdb:
    external: true
